-- Web Product Catalog MySQL Setup Script
--
--
-- CREATE DATABASE IF NOT EXISTS web_product_catalog;
-- CREATE USER IF NOT EXISTS 'web_product_catalog'@'localhost' IDENTIFIED BY 'webProductCatalog';

-- creates the category table
-- description: id INT, name VARCHAR(256) can’t be null
CREATE TABLE IF NOT EXISTS `categories` (
    `id`   BIGINT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL UNIQUE
);

-- create products table
-- decription:
--  product_id: product id, auto generated by the RDBMS and not empty
--  name: name of product, required
--  description: product description,
--  image_url: product image name and location,
--  price: product price,
--  category_id: product category id

CREATE TABLE IF NOT EXISTS `products` (
    `product_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `image_url`  VARCHAR(255) NOT NULL,
    `price` INT,
    `category_id` BIGINT NOT NULL,
    FOREIGN KEY(`category_id`) REFERENCES categories(`id`)
)